javascript_compressor: closure
package_path: "javascripts/"
gzip_assets: off

javascripts:
  app:
    - public/javascripts/vendor/jquery-1.8.2.js
    - public/javascripts/vendor/ACE-noconflict/ace.js
    - public/javascripts/vendor/ACE-noconflict/mode-css.js
    - public/javascripts/vendor/ACE-noconflict/mode-scss.js
    - public/javascripts/vendor/ACE-noconflict/theme-tomorrow.js
    - public/javascripts/vendor/ACE-noconflict/worker-css.js
    - public/javascripts/vendor/jquery.foundation.reveal.js
    - public/javascripts/vendor/chosen.jquery.js
    - public/javascripts/main.js

# stylesheets:
#   common:
#     - public/stylesheets/reset.css
#     - public/stylesheets/widgets/*.css
#   workspace:
#     - public/stylesheets/pages/workspace.css
#   empty:
#     - public/stylesheets/pages/empty.css