javascript_compressor: closure
# compressor_options:
#   compilation_level: "ADVANCED_OPTIMIZATIONS"
package_path: "js/"
gzip_assets: off

javascripts:
  embed:
    - javascripts/compiled/embed.js

  jquery:
    - javascripts/vendor/jquery-2.1.0.js

  utilities:    
    - javascripts/vendor/ACE-noconflict/ace.js
    - javascripts/vendor/ACE-noconflict/mode-css.js
    - javascripts/vendor/ACE-noconflict/mode-sass.js
    - javascripts/vendor/ACE-noconflict/mode-scss.js
    - javascripts/vendor/ACE-noconflict/mode-html.js
    - javascripts/vendor/ACE-noconflict/mode-haml.js
    - javascripts/vendor/ACE-noconflict/mode-jade.js
    - javascripts/vendor/ACE-noconflict/mode-markdown.js
    - javascripts/vendor/ACE-noconflict/mode-textile.js
    - javascripts/vendor/ACE-noconflict/ext-emmet.js
    - javascripts/vendor/ACE-noconflict/keybinding-vim.js
    # Themes - light
    - javascripts/vendor/ACE-noconflict/theme-dawn.js
    - javascripts/vendor/ACE-noconflict/theme-github.js
    - javascripts/vendor/ACE-noconflict/theme-kuroir.js
    - javascripts/vendor/ACE-noconflict/theme-solarized_light.js
    - javascripts/vendor/ACE-noconflict/theme-tomorrow.js
    # Themes - dark
    - javascripts/vendor/ACE-noconflict/theme-merbivore_soft.js
    - javascripts/vendor/ACE-noconflict/theme-monokai.js
    - javascripts/vendor/ACE-noconflict/theme-solarized_dark.js
    - javascripts/vendor/ACE-noconflict/theme-tomorrow_night_eighties.js

    - javascripts/vendor/bindWithDelay.js
    - javascripts/vendor/messenger.min.js
    - javascripts/vendor/casement.js
    - javascripts/vendor/fancy_dropdown.js
    - javascripts/viewport.js

  application:
    - javascripts/messages.js
    - javascripts/SassMeister.js
    - javascripts/main.js

  modernizr:
    - javascripts/modernizr.js

  jade:
    - javascripts/vendor/jade-1.3.0.js

# stylesheets:
#   common:
#     - stylesheets/reset.css
#     - stylesheets/widgets/*.css
#   workspace:
#     - stylesheets/pages/workspace.css
#   empty:
#     - stylesheets/pages/empty.css
