Bitters:
  :gem: bitters-compass
  :import:
    - bourbon/bourbon
    - neat/neat
    - bitters/bitters
  :fingerprint: (bitters|bitters/*)
  :url: http://bitters.bourbon.io
"Blend Modes":
  :gem: blend-mode
  :import: 
    - blend-modes
  :fingerprint: blend-mode*
  :url: https://github.com/heygrady/scss-blend-modes
Bourbon:
  :gem: bourbon-compass
  :import: 
    - bourbon/bourbon
  :fingerprint: (bourbon|bourbon/*)
  :url: http://bourbon.io/
Breakpoint:
  :gem: breakpoint
  :import: 
    - breakpoint
  :fingerprint: breakpoint
  :url: https://github.com/canarymason/breakpoint
"Breakpoint Slicer":
  :gem: breakpoint-slicer
  :import:
    - breakpoint-slicer
  :fingerprint: breakpoint-slicer
  :url: https://github.com/lolmaus/breakpoint-slicer
Breakup:
  :gem: breakup
  :import: 
    - breakup
  :fingerprint: breakup
  :url: https://github.com/BPScott/breakup
"Color Schemer":
  :gem: color-schemer
  :import: 
    - color-schemer
  :fingerprint: color-schemer
  :url: https://github.com/Team-Sass/color-schemer
Compass:
  :gem: compass
  :import: 
    - compass
  :fingerprint: (compass|compass/*)
  :url: http://compass-style.org
"Compass Placeholders":
  :gem: compass-placeholders
  :import:
    - compass
    - compass-placeholders
  :fingerprint: compass-placeholders
  :url: https://github.com/hagenburger/compass-placeholders
"Compass Slideshow":
  :gem: css-slideshow
  :import: 
    - css-slideshow
  :fingerprint: css-slideshow
  :url: https://github.com/ericam/compass-css-slideshow
"Fancy Buttons":
  :gem: fancy-buttons
  :import: 
    - fancy-buttons
  :fingerprint: fancy-buttons
  :url: http://brandonmathis.com/projects/fancy-buttons/
Fittext:
  :gem: fittext
  :import: 
    - fittext
  :fingerprint: fittext
  :url: http://www.bookcasey.com/fittext/
Foundation:
  :gem: zurb-foundation
  :import:
    - foundation
  :fingerprint: foundation*
  :url: http://foundation.zurb.com/docs/sass.html
"Grid Coordinates":
  :gem: grid-coordinates
  :import: 
    - grid-coordinates
  :fingerprint: grid-coordinates
  :url: https://github.com/adamstac/grid-coordinates
Harsh:
  :gem: harsh
  :import: 
    - harsh
  :fingerprint: harsh
  :url: http://www.bookcasey.com/harsh/
Compass Inuit:
  :gem: compass-inuit
  :import: 
    - compass-inuit
  :fingerprint: compass-inuit*
  :url: https://github.com/stephenway/compass-inuit
Jacket:
  :gem: jacket
  :import:
    - jacket
  :fingerprint: jacket
  :url: https://github.com/Team-Sass/jacket
"Modular Scale":
  :gem: modular-scale
  :import: 
    - modular-scale
  :fingerprint: modular-scale
  :url: https://github.com/Team-Sass/modular-scale
Neat:
  :gem: neat-compass
  :import:
    - bourbon/bourbon
    - neat/neat
  :fingerprint: (neat|neat/*)
  :url: http://neat.bourbon.io
'Normalize SCSS':
  :gem: normalize-scss
  :import:
    - normalize-scss
  :fingerprint: normalize-scss
  :url: https://github.com/JohnAlbin/normalize.css-with-sass-or-compass
"Photoshop Drop Shadow":
  :gem: compass-photoshop-drop-shadow
  :import: 
    - photoshop-drop-shadow
  :fingerprint: photoshop-drop-shadow
  :url: https://github.com/heygrady/compass-photoshop-drop-shadow
"Responsive Calculator":
  :gem: rwdcalc
  :import: 
    - rwdcalc
  :fingerprint: rwdcalc
  :url: https://github.com/sturobson/Responsive-Calculator/tree/rwdcalcSass/SCSSMixin
"Responsive Sass":
  :gem: responsive-sass
  :import: 
    - responsive-sass
  :fingerprint: responsive-sass
  :url: http://ntreadway.github.com/responsive-sass/welcome
Salsa:
  :gem: salsa
  :import: 
    - salsa
  :fingerprint: salsa
  :url: http://tsi.github.com/Salsa/
"Sassy Buttons":
  :gem: sassy-buttons
  :import: 
    - sassy-buttons
  :fingerprint: sassy-buttons
  :url: http://jaredhardy.com/sassy-buttons/
# "Sassy Math":
#   :gem: sassy-math
#   :import: 
#     - '' # This space intentionally left blank 
#   :url: https://github.com/Team-Sass/Sassy-math
"Sassy Maps":
  :gem: sassy-maps
  :import: 
    - sassy-maps
  :fingerprint: sassy-maps
  :url: https://github.com/Team-Sass/Sassy-Maps
"Sassy Text Shadow":
  :gem: sassy-text-shadow
  :import:
    - compass
    - sassy-text-shadow
  :fingerprint: sassy-text-shadow
  :url: http://sassymothereffingtextshadow.com/
SassyLists:
  :gem: SassyLists
  :import:
    - SassyLists
  :fingerprint: SassyLists
  :url: http://sassylists.com/
Singularity.gs:
  :gem: singularitygs
  :import: 
    - singularitygs
  :fingerprint: singularitygs
  :url: https://github.com/Team-Sass/singularity
"Singularity Extras":
  :gem: singularity-extras
  :import:
    - singularitygs
    - singularity-extras
  :fingerprint: singularity-extras
  :url: https://github.com/Team-Sass/Singularity-extras
"Singularity Golden Grid":
  :gem: singularity-golden-grid
  :import:
    - singularitygs
    - singularity-golden-grid
  :fingerprint: singularity-golden-grid
  :url: https://github.com/hunterman/singularity-golden-grid
Stipe:
  :gem: stipe
  :import: 
    - stipe/manifest
    - stipe/grid/extends
  :fingerprint: (stipe|stipe/*)
  :url: https://github.com/Toadstool-Stipe/stipe
Stitch:
  :gem: stitch
  :import: 
    - stitch
  :fingerprint: stitch
  :url: http://anthonyshort.github.io/stitch-css/
Susy:
  :gem: susy
  :import: 
    - susy
  :fingerprint: susy
  :url: http://susy.oddbird.net
Toolkit:
  :gem: toolkit
  :import: 
    - toolkit
  :fingerprint: toolkit
  :url: https://github.com/Team-Sass/toolkit
"True":
  :gem: "true"
  :import:
    - "true"
  :fingerprint: "true"
  :url: https://github.com/ericam/true
"Zen Grids":
  :gem: zen-grids
  :import: 
    - zen
  :fingerprint: (zen|zen-grids)
  :url: http://zengrids.com/
